// 会話練習シナリオ
// turns: 相手(ai)のセリフと、ユーザーが返す模範解答(answers)。hint は日本語の言いたいこと。
const SCENARIOS = [
  {
    id: 'intro', emoji: '👋', name: '自己紹介', desc: '初対面の人と話す',
    turns: [
      { ai: "Hi there! I'm Emma. What's your name?", ja: 'こんにちは！エマです。お名前は？',
        hint: '自分の名前を伝えよう', answers: ["Hi Emma, my name is Ken.", "Nice to meet you, I'm Ken.", "Hello, I'm Ken. Nice to meet you."] },
      { ai: "Nice to meet you! Where are you from?", ja: 'はじめまして！どちらの出身ですか？',
        hint: '日本の出身だと伝えよう', answers: ["I'm from Japan.", "I'm from Tokyo, Japan.", "I come from Japan."] },
      { ai: "Oh, cool! What do you do?", ja: 'へえ、いいね！お仕事は何をしていますか？',
        hint: '仕事を説明しよう（例：エンジニア）', answers: ["I work as an engineer.", "I'm a software engineer.", "I'm an office worker."] },
      { ai: "That sounds interesting. What do you like to do in your free time?", ja: '面白そう。暇なときは何をするのが好き？',
        hint: '趣味を伝えよう', answers: ["I like watching movies.", "I enjoy reading books and playing tennis.", "I like to travel in my free time."] },
      { ai: "Great! It was nice talking to you.", ja: 'いいね！話せてよかったです。',
        hint: 'こちらこそ、と返そう', answers: ["It was nice talking to you too.", "Nice talking to you too. See you!", "Same here. Have a nice day!"] },
    ],
  },
  {
    id: 'restaurant', emoji: '🍽️', name: 'レストラン', desc: '注文・会計をする',
    turns: [
      { ai: "Good evening! How many people are in your party?", ja: 'こんばんは！何名様ですか？',
        hint: '2人だと伝えよう', answers: ["Two, please.", "A table for two, please.", "There are two of us."] },
      { ai: "Right this way. Can I get you something to drink?", ja: 'こちらへどうぞ。お飲み物はいかがですか？',
        hint: '水をお願いしよう', answers: ["Just water, please.", "Can I have some water, please?", "I'll have a glass of water, please."] },
      { ai: "Are you ready to order?", ja: 'ご注文はお決まりですか？',
        hint: 'ハンバーガーを注文しよう', answers: ["Yes, I'd like the hamburger, please.", "I'll have the hamburger.", "Can I get the hamburger, please?"] },
      { ai: "Would you like fries or a salad with that?", ja: 'ポテトとサラダ、どちらになさいますか？',
        hint: 'サラダを選ぼう', answers: ["Salad, please.", "I'll have a salad, please.", "A salad would be great."] },
      { ai: "How is everything tasting?", ja: 'お味はいかがですか？',
        hint: 'とてもおいしいと伝えよう', answers: ["Everything is delicious, thank you.", "It's really good, thanks.", "It's great, thank you."] },
      { ai: "Can I get you anything else?", ja: '他に何かお持ちしましょうか？',
        hint: 'お会計をお願いしよう', answers: ["Could we get the check, please?", "Just the check, please.", "Can I have the bill, please?"] },
    ],
  },
  {
    id: 'airport', emoji: '✈️', name: '空港・入国審査', desc: 'チェックインと入国審査',
    turns: [
      { ai: "May I see your passport, please?", ja: 'パスポートを拝見できますか？',
        hint: 'はい、どうぞと渡そう', answers: ["Here you are.", "Sure, here it is.", "Here is my passport."] },
      { ai: "What's the purpose of your visit?", ja: '訪問の目的は何ですか？',
        hint: '観光だと伝えよう', answers: ["Sightseeing.", "I'm here for sightseeing.", "I'm here on vacation."] },
      { ai: "How long will you be staying?", ja: 'どのくらい滞在しますか？',
        hint: '1週間だと伝えよう', answers: ["For one week.", "I'll be staying for a week.", "About one week."] },
      { ai: "Where will you be staying?", ja: 'どこに滞在しますか？',
        hint: 'ヒルトンホテルに泊まると伝えよう', answers: ["At the Hilton Hotel.", "I'll be staying at the Hilton Hotel.", "I'm staying at the Hilton."] },
      { ai: "Do you have anything to declare?", ja: '申告するものはありますか？',
        hint: 'ありません、と答えよう', answers: ["No, nothing to declare.", "No, I don't.", "No, I have nothing to declare."] },
    ],
  },
  {
    id: 'hotel', emoji: '🏨', name: 'ホテル', desc: 'チェックインと要望',
    turns: [
      { ai: "Welcome! How can I help you?", ja: 'いらっしゃいませ！ご用件は？',
        hint: 'チェックインしたいと伝えよう', answers: ["I'd like to check in, please.", "I have a reservation. I'd like to check in.", "Check in, please."] },
      { ai: "May I have your name, please?", ja: 'お名前をいただけますか？',
        hint: '名前を伝えよう', answers: ["It's Ken Tanaka.", "My name is Ken Tanaka.", "The reservation is under Tanaka."] },
      { ai: "Thank you. You're in room 512. Is there anything else?", ja: 'ありがとうございます。512号室です。他に何か？',
        hint: '朝食の時間を聞こう', answers: ["What time is breakfast?", "What time is breakfast served?", "When is breakfast?"] },
      { ai: "Breakfast is from 7 to 10 a.m. on the second floor.", ja: '朝食は2階で7時から10時です。',
        hint: 'Wi-Fiのパスワードを聞こう', answers: ["What's the Wi-Fi password?", "Could you tell me the Wi-Fi password?", "Can I have the Wi-Fi password, please?"] },
      { ai: "It's on your key card holder. Enjoy your stay!", ja: 'カードキーのケースに書いてあります。ごゆっくりどうぞ！',
        hint: 'お礼を言おう', answers: ["Thank you very much.", "Thanks a lot.", "Thank you, have a nice day."] },
    ],
  },
  {
    id: 'shopping', emoji: '🛍️', name: '買い物', desc: 'サイズや値段を聞く',
    turns: [
      { ai: "Hi! Can I help you find something?", ja: 'こんにちは！何かお探しですか？',
        hint: '見ているだけです、と伝えよう', answers: ["I'm just looking, thanks.", "Just looking, thank you.", "No thanks, I'm just browsing."] },
      { ai: "Sure, let me know if you need anything.", ja: 'はい、何かあればお声がけください。',
        hint: 'このシャツのMサイズはあるか聞こう', answers: ["Do you have this shirt in a medium?", "Do you have this in medium?", "Is there a medium size for this shirt?"] },
      { ai: "Yes, here you go. Would you like to try it on?", ja: 'はい、どうぞ。試着されますか？',
        hint: '試着室の場所を聞こう', answers: ["Yes, where is the fitting room?", "Yes please. Where are the fitting rooms?", "Sure, where can I try it on?"] },
      { ai: "How does it fit?", ja: 'サイズはいかがですか？',
        hint: 'ぴったりです、いくらですか？', answers: ["It fits perfectly. How much is it?", "It's perfect. How much is this?", "It fits well. How much does it cost?"] },
      { ai: "It's 35 dollars. How would you like to pay?", ja: '35ドルです。お支払いはどうされますか？',
        hint: 'カードで払おう', answers: ["By credit card, please.", "Can I pay by card?", "I'll pay with my credit card."] },
    ],
  },
  {
    id: 'directions', emoji: '🗺️', name: '道を尋ねる', desc: '駅や場所への行き方',
    turns: [
      { ai: "Hi, you look lost. Can I help you?", ja: '迷っているようですね。お手伝いしましょうか？',
        hint: '駅への行き方を聞こう', answers: ["Yes, how do I get to the station?", "Could you tell me the way to the station?", "Excuse me, where is the train station?"] },
      { ai: "Go straight for two blocks and turn left.", ja: '2ブロックまっすぐ行って左に曲がってください。',
        hint: '歩いてどのくらいか聞こう', answers: ["How long does it take on foot?", "How long will it take to walk there?", "Is it far from here?"] },
      { ai: "About ten minutes on foot.", ja: '歩いて約10分です。',
        hint: '近くにコンビニがあるかも聞こう', answers: ["Is there a convenience store nearby?", "Is there a convenience store near here?", "Where is the nearest convenience store?"] },
      { ai: "Yes, there's one right next to the station.", ja: 'はい、駅のすぐ隣にありますよ。',
        hint: '丁寧にお礼を言おう', answers: ["Thank you so much for your help.", "Thanks, you've been very helpful.", "Thank you very much."] },
    ],
  },
  {
    id: 'cafe', emoji: '☕', name: 'カフェ', desc: 'コーヒーを注文する',
    turns: [
      { ai: "Hi! What can I get for you?", ja: 'こんにちは！ご注文は？',
        hint: 'ラテのMサイズを注文しよう', answers: ["Can I get a medium latte, please?", "I'd like a medium latte, please.", "A medium latte, please."] },
      { ai: "Hot or iced?", ja: 'ホットとアイス、どちらにしますか？',
        hint: 'アイスで', answers: ["Iced, please.", "I'll have it iced.", "Iced, please. Thank you."] },
      { ai: "For here or to go?", ja: '店内でお召し上がりですか、お持ち帰りですか？',
        hint: '持ち帰りで', answers: ["To go, please.", "It's to go.", "I'll take it to go."] },
      { ai: "Can I get a name for the order?", ja: 'ご注文のお名前をいただけますか？',
        hint: '名前を伝えよう', answers: ["It's Ken.", "Ken, please.", "My name is Ken."] },
    ],
  },
  {
    id: 'doctor', emoji: '🏥', name: '病院・薬局', desc: '症状を伝える',
    turns: [
      { ai: "What seems to be the problem today?", ja: '今日はどうされましたか？',
        hint: '頭痛がすると伝えよう', answers: ["I have a headache.", "I've had a bad headache.", "My head hurts."] },
      { ai: "How long have you had it?", ja: 'いつからですか？',
        hint: '昨日からと伝えよう', answers: ["Since yesterday.", "I've had it since yesterday.", "It started yesterday."] },
      { ai: "Do you have a fever?", ja: '熱はありますか？',
        hint: '少し熱があると伝えよう', answers: ["Yes, I have a slight fever.", "I have a little fever.", "Yes, a little."] },
      { ai: "Are you allergic to any medicine?", ja: '薬のアレルギーはありますか？',
        hint: 'ありません', answers: ["No, I'm not allergic to anything.", "No, I don't have any allergies.", "No, I'm not."] },
    ],
  },
  {
    id: 'taxi', emoji: '🚕', name: 'タクシー', desc: '行き先を伝える',
    turns: [
      { ai: "Hi, where to?", ja: 'どちらまで？',
        hint: 'セントラル駅までお願いしよう', answers: ["To Central Station, please.", "Central Station, please.", "Could you take me to Central Station?"] },
      { ai: "Sure. Are you in a hurry?", ja: 'かしこまりました。お急ぎですか？',
        hint: '3時の電車に乗りたいと伝えよう', answers: ["Yes, I need to catch a train at three.", "Yes, my train leaves at three.", "A little. I have a train at three o'clock."] },
      { ai: "No problem. We should get there in about fifteen minutes.", ja: '大丈夫です。15分ほどで着くと思います。',
        hint: 'エアコンを弱めてもらえるか聞こう', answers: ["Could you turn down the air conditioner?", "Can you turn the AC down a little?", "Could you make it a little warmer, please?"] },
      { ai: "Here we are. That'll be eighteen dollars.", ja: '着きました。18ドルです。',
        hint: '20ドル渡して、お釣りはいらないと伝えよう', answers: ["Here's twenty. Keep the change.", "Here you go. Keep the change.", "Here is twenty dollars. Please keep the change."] },
      { ai: "Thank you! Have a safe trip.", ja: 'ありがとうございます！よい旅を。',
        hint: 'お礼を言おう', answers: ["Thank you. Have a nice day.", "Thanks, you too.", "Thank you very much."] },
    ],
  },
  {
    id: 'train', emoji: '🚆', name: '駅・電車', desc: '切符を買う・乗り換え',
    turns: [
      { ai: "Next, please. How can I help you?", ja: '次の方どうぞ。ご用件は？',
        hint: 'ボストンまでの往復切符を1枚買おう', answers: ["One round-trip ticket to Boston, please.", "I'd like a round-trip ticket to Boston.", "Can I get a return ticket to Boston?"] },
      { ai: "Sure. That's forty-five dollars. The next train leaves at 10:30.", ja: 'はい、45ドルです。次の電車は10時30分発です。',
        hint: '何番線から出るか聞こう', answers: ["Which platform does it leave from?", "What platform is it?", "Which track does the train leave from?"] },
      { ai: "Platform 4. It's down the stairs on your right.", ja: '4番線です。右手の階段を下りたところです。',
        hint: '乗り換えが必要か聞こう', answers: ["Do I need to change trains?", "Do I have to transfer?", "Is it a direct train?"] },
      { ai: "No, it's a direct train. It takes about two hours.", ja: 'いいえ、直通です。約2時間かかります。',
        hint: 'お礼を言おう', answers: ["Great, thank you.", "Thank you for your help.", "Perfect. Thanks a lot."] },
    ],
  },
  {
    id: 'phone', emoji: '📞', name: '電話で予約', desc: 'レストランを予約する',
    turns: [
      { ai: "Hello, Bella Italia. How may I help you?", ja: 'はい、ベラ・イタリアです。ご用件をどうぞ。',
        hint: '予約をしたいと伝えよう', answers: ["Hi, I'd like to make a reservation.", "I'd like to book a table, please.", "Hello, can I make a reservation?"] },
      { ai: "Of course. For what day and time?", ja: 'かしこまりました。何日の何時ですか？',
        hint: '今週の土曜の夜7時で', answers: ["This Saturday at 7 p.m.", "Saturday at seven, please.", "For this Saturday at seven in the evening."] },
      { ai: "And how many people?", ja: '何名様ですか？',
        hint: '4人です', answers: ["Four people.", "There will be four of us.", "A table for four, please."] },
      { ai: "Could I have your name and phone number?", ja: 'お名前とお電話番号をいただけますか？',
        hint: '名前と番号を伝えよう', answers: ["It's Ken Tanaka, and my number is 555-1234.", "My name is Tanaka. My number is 555-1234.", "Tanaka, 555-1234."] },
      { ai: "Great, you're all set. Is there anything else?", ja: 'ご予約完了です。他に何かございますか？',
        hint: '窓際の席をお願いできるか聞こう', answers: ["Could we have a table by the window?", "Is it possible to get a window seat?", "Can we sit by the window?"] },
    ],
  },
  {
    id: 'invite', emoji: '🎉', name: '友達を誘う', desc: '予定を立てる',
    turns: [
      { ai: "Hey! What are you up to this weekend?", ja: 'やあ！今週末は何するの？',
        hint: '特に予定はないと伝えよう', answers: ["Nothing special. How about you?", "I don't have any plans yet.", "Not much. What about you?"] },
      { ai: "I'm thinking of going to the beach. Want to come?", ja: 'ビーチに行こうと思ってるんだ。一緒に来る？',
        hint: 'ぜひ行きたい！', answers: ["Sure, I'd love to!", "That sounds great. Count me in!", "Yes, I'd love to come."] },
      { ai: "Awesome! How about Saturday morning?", ja: 'いいね！土曜の朝はどう？',
        hint: '何時に待ち合わせるか聞こう', answers: ["Sounds good. What time should we meet?", "Saturday works. What time?", "Great. Where and when should we meet?"] },
      { ai: "Let's meet at the station at nine.", ja: '9時に駅で待ち合わせよう。',
        hint: '何か持っていくものがあるか聞こう', answers: ["Okay. Should I bring anything?", "Got it. Do I need to bring anything?", "Sure. What should I bring?"] },
      { ai: "Just a towel and some sunscreen. See you then!", ja: 'タオルと日焼け止めだけでいいよ。じゃあね！',
        hint: '楽しみにしてる、と伝えよう', answers: ["I can't wait. See you!", "Looking forward to it. See you Saturday!", "Great, see you then!"] },
    ],
  },
  {
    id: 'meeting', emoji: '💼', name: '会議', desc: '仕事で意見を伝える',
    turns: [
      { ai: "Thanks for joining. Could you give us an update on the project?", ja: 'ご参加ありがとうございます。プロジェクトの進捗を教えてもらえますか？',
        hint: '予定通り進んでいると伝えよう', answers: ["Sure. The project is on schedule.", "We're on track with the project.", "Everything is going according to plan."] },
      { ai: "Great. Are there any issues we should know about?", ja: 'いいですね。知っておくべき問題はありますか？',
        hint: 'テストに少し時間がかかっていると伝えよう', answers: ["Testing is taking a little longer than expected.", "The testing phase is taking more time than we planned.", "We have a small delay in testing."] },
      { ai: "I see. What do you suggest?", ja: 'なるほど。どうしたらいいと思いますか？',
        hint: 'もう1人メンバーを追加したい', answers: ["I suggest adding one more person to the team.", "I think we need one more team member.", "Could we add another person to the team?"] },
      { ai: "That makes sense. Can you send me the details by Friday?", ja: 'なるほど。金曜日までに詳細を送ってもらえますか？',
        hint: 'もちろんです', answers: ["Of course. I'll send them by Friday.", "Sure, I'll email you the details by Friday.", "No problem. I'll send it by Friday."] },
    ],
  },
  {
    id: 'exchange', emoji: '💱', name: '両替・銀行', desc: 'お金を両替する',
    turns: [
      { ai: "Good morning. What can I do for you?", ja: 'おはようございます。ご用件は？',
        hint: '円をドルに両替したい', answers: ["I'd like to exchange yen for dollars.", "Can I change some yen into dollars?", "I want to exchange Japanese yen to US dollars."] },
      { ai: "Sure. How much would you like to exchange?", ja: 'かしこまりました。いくら両替しますか？',
        hint: '3万円です', answers: ["Thirty thousand yen, please.", "I'd like to exchange 30,000 yen.", "30,000 yen, please."] },
      { ai: "May I see your ID, please?", ja: '身分証を拝見できますか？',
        hint: 'パスポートを渡そう', answers: ["Here's my passport.", "Sure, here you are.", "Here is my passport."] },
      { ai: "Thank you. How would you like your bills?", ja: 'ありがとうございます。紙幣の内訳はどうしますか？',
        hint: '20ドル札でお願いしよう', answers: ["Twenties, please.", "In twenty-dollar bills, please.", "Could I have them in twenties?"] },
      { ai: "Here you go. Please check the amount.", ja: 'どうぞ。金額をご確認ください。',
        hint: '大丈夫です、ありがとう', answers: ["That's correct. Thank you.", "It's all there. Thanks.", "Everything looks fine. Thank you."] },
    ],
  },
  {
    id: 'lost', emoji: '🆘', name: 'トラブル・落とし物', desc: '困ったときに助けを求める',
    turns: [
      { ai: "Hello, this is the lost and found. How can I help?", ja: 'こちら遺失物取扱所です。どうしましたか？',
        hint: '財布をなくしたと伝えよう', answers: ["I lost my wallet.", "I think I lost my wallet.", "I can't find my wallet."] },
      { ai: "I'm sorry to hear that. Where did you last have it?", ja: 'それはお気の毒に。最後に持っていたのはどこですか？',
        hint: '電車の中だと思う', answers: ["I think I left it on the train.", "Probably on the train.", "I had it on the train."] },
      { ai: "Can you describe it?", ja: 'どんな財布か説明できますか？',
        hint: '黒い革の財布です', answers: ["It's a black leather wallet.", "It's black and made of leather.", "A small black leather wallet."] },
      { ai: "Let me check... Is this yours?", ja: '確認しますね…これですか？',
        hint: 'はい、それです！', answers: ["Yes, that's mine! Thank you so much!", "Yes, that's it!", "That's my wallet. Thank you!"] },
    ],
  },
  {
    id: 'homestay', emoji: '🏠', name: 'ホームステイ', desc: 'ホストファミリーと話す',
    turns: [
      { ai: "Welcome to our home! How was your flight?", ja: 'ようこそ我が家へ！フライトはどうだった？',
        hint: '長かったけど快適だった', answers: ["It was long, but comfortable.", "It was a long flight, but it was fine.", "Long, but I was able to sleep."] },
      { ai: "You must be tired. Are you hungry?", ja: '疲れたでしょう。お腹すいてる？',
        hint: '少しすいている', answers: ["Yes, a little.", "I'm a little hungry.", "Yes, I'm kind of hungry."] },
      { ai: "Great, dinner will be ready soon. Is there anything you can't eat?", ja: 'よかった、夕食はもうすぐできるよ。食べられないものはある？',
        hint: '何でも食べられる', answers: ["No, I can eat anything.", "I can eat everything.", "Nothing, I'm not picky."] },
      { ai: "Perfect. Please make yourself at home.", ja: 'よかった。くつろいでね。',
        hint: 'シャワーを使ってもいいか聞こう', answers: ["Thank you. May I take a shower?", "Can I use the shower?", "Is it okay if I take a shower?"] },
      { ai: "Of course! Towels are in the bathroom.", ja: 'もちろん！タオルはお風呂場にあるよ。',
        hint: '温かく迎えてくれてありがとう', answers: ["Thank you for having me.", "Thank you for welcoming me.", "Thanks for everything."] },
    ],
  },
  {
    id: 'movie', emoji: '🎬', name: '映画館', desc: 'チケットと売店',
    turns: [
      { ai: "Hi, which movie would you like to see?", ja: 'こんにちは、どの映画をご覧になりますか？',
        hint: '7時の回を大人2枚', answers: ["Two adults for the seven o'clock show, please.", "Two tickets for the 7 p.m. show, please.", "Two adult tickets for the seven o'clock, please."] },
      { ai: "Where would you like to sit?", ja: 'どの辺りの席がよろしいですか？',
        hint: '真ん中あたりで', answers: ["Somewhere in the middle, please.", "In the middle, please.", "Middle seats, if possible."] },
      { ai: "Here are your tickets. Would you like any snacks?", ja: 'チケットです。何か軽食はいかがですか？',
        hint: 'ポップコーンのLとコーラを2つ', answers: ["A large popcorn and two Cokes, please.", "Can I get a large popcorn and two Cokes?", "I'll have a large popcorn and two colas."] },
      { ai: "Salted or butter?", ja: '塩とバター、どちらにしますか？',
        hint: 'バターで', answers: ["Butter, please.", "I'll have butter.", "Butter, thanks."] },
    ],
  },
  {
    id: 'supermarket', emoji: '🛒', name: 'スーパー', desc: '売り場を探す・レジ',
    turns: [
      { ai: "Hi there. Can I help you find something?", ja: 'こんにちは。何かお探しですか？',
        hint: '牛乳はどこか聞こう', answers: ["Yes, where can I find the milk?", "Where is the milk?", "Excuse me, which aisle is the milk in?"] },
      { ai: "It's in aisle five, next to the eggs.", ja: '5番通路の卵の隣です。',
        hint: 'ありがとう', answers: ["Thank you.", "Thanks a lot.", "Great, thanks."] },
      { ai: "Next customer, please. Do you need a bag?", ja: '次のお客様どうぞ。袋はいりますか？',
        hint: 'いりません、エコバッグがある', answers: ["No, thanks. I have my own bag.", "No, I brought my own bag.", "I don't need one, thanks."] },
      { ai: "Your total is twelve fifty. Do you have a membership card?", ja: '合計12ドル50セントです。会員カードはお持ちですか？',
        hint: '持っていません', answers: ["No, I don't.", "No, I don't have one.", "Sorry, I don't have one."] },
    ],
  },
];

// 発音練習フレーズ
const PHRASES = {
  'あいさつ': [
    ['How are you doing?', '調子はどう？'],
    ["Nice to meet you.", 'はじめまして。'],
    ["Long time no see.", '久しぶり。'],
    ["Have a nice weekend.", '良い週末を。'],
    ["See you later.", 'また後でね。'],
    ["Thank you for your help.", '助けてくれてありがとう。'],
    ["What's up?", '最近どう？'],
    ["How have you been?", '元気にしてた？'],
    ["It was nice talking to you.", '話せてよかったです。'],
    ["Take care.", '気をつけてね。'],
    ["Sorry to keep you waiting.", 'お待たせしてすみません。'],
    ["Say hello to your family for me.", 'ご家族によろしく。'],
  ],
  'リアクション': [
    ["That sounds great!", 'それはいいね！'],
    ["No way!", 'まさか！'],
    ["I know what you mean.", 'わかるよ。'],
    ["That's too bad.", 'それは残念。'],
    ["Good for you!", 'よかったね！'],
    ["I couldn't agree more.", '大賛成です。'],
    ["Are you serious?", '本気で言ってるの？'],
    ["It's up to you.", 'あなたに任せるよ。'],
    ["No worries.", '気にしないで。'],
    ["I'm not sure about that.", 'それはどうかな。'],
  ],
  '旅行': [
    ["Where is the nearest station?", '最寄り駅はどこですか？'],
    ["How much is this?", 'これはいくらですか？'],
    ["Could you take a picture of us?", '写真を撮っていただけますか？'],
    ["I'd like to make a reservation.", '予約をしたいのですが。'],
    ["Can I pay by credit card?", 'クレジットカードで払えますか？'],
    ["Is this seat taken?", 'この席は空いていますか？'],
    ["What time does it open?", '何時に開きますか？'],
    ["Could you recommend a good restaurant?", 'おすすめのレストランはありますか？'],
    ["I'm looking for this address.", 'この住所を探しています。'],
    ["Can I get a map, please?", '地図をもらえますか？'],
    ["Where can I buy a ticket?", '切符はどこで買えますか？'],
  ],
  'レストラン・買い物': [
    ["Can I see the menu, please?", 'メニューを見せてもらえますか？'],
    ["What do you recommend?", 'おすすめは何ですか？'],
    ["I'll have the same.", '同じものをください。'],
    ["Could I get a refill?", 'おかわりをもらえますか？'],
    ["Can I get this to go?", 'これを持ち帰りにできますか？'],
    ["Can I try this on?", '試着してもいいですか？'],
    ["Do you have this in a smaller size?", 'これの小さいサイズはありますか？'],
    ["I'm just looking, thanks.", '見ているだけです。'],
    ["Could I get a receipt?", 'レシートをもらえますか？'],
    ["Is there a discount?", '割引はありますか？'],
  ],
  '仕事': [
    ["Let me check and get back to you.", '確認して折り返します。'],
    ["Could you send me the details?", '詳細を送っていただけますか？'],
    ["I'm afraid I can't make it.", '残念ながら行けそうにありません。'],
    ["Let's schedule a meeting.", 'ミーティングを設定しましょう。'],
    ["That makes sense.", 'なるほど、納得です。'],
    ["Could you say that again, please?", 'もう一度言っていただけますか？'],
    ["I'll keep you posted.", '随時お知らせします。'],
    ["What's the deadline?", '締め切りはいつですか？'],
    ["Let's move on to the next topic.", '次の議題に移りましょう。'],
    ["I'd like to share my screen.", '画面を共有したいです。'],
    ["Sorry, you're on mute.", 'すみません、ミュートになっていますよ。'],
    ["Thank you for your time today.", '本日はお時間をいただきありがとうございました。'],
  ],
  '電話': [
    ["May I ask who's calling?", 'どちら様ですか？'],
    ["Could I speak to Mr. Smith?", 'スミスさんとお話しできますか？'],
    ["Hold on a moment, please.", '少々お待ちください。'],
    ["He's not available right now.", '彼は今席を外しています。'],
    ["Can I leave a message?", '伝言をお願いできますか？'],
    ["Could you speak a little more slowly?", 'もう少しゆっくり話していただけますか？'],
    ["I'll call you back later.", '後でかけ直します。'],
    ["Sorry, I think I have the wrong number.", 'すみません、番号を間違えたようです。'],
  ],
  '数字・日付': [
    ['thirteen and thirty', '13と30'],
    ['fifteen and fifty', '15と50'],
    ['nineteen ninety-nine', '1999年'],
    ['two thousand twenty-six', '2026年'],
    ['It costs twelve dollars and fifty cents.', '12ドル50セントです。'],
    ['My birthday is on March third.', '誕生日は3月3日です。'],
    ["The meeting is on Wednesday at eleven thirty.", '会議は水曜日の11時半です。'],
    ['My phone number is five five five, one two three four.', '電話番号は555-1234です。'],
  ],
  'L と R': [
    ['right and light', '右と光'],
    ['read and lead', '読むと導く'],
    ['rice and lice', '米とシラミ'],
    ['really', '本当に'],
    ['The rabbit likes red carrots.', 'ウサギは赤いニンジンが好き。'],
    ['Lily rarely rides the rollercoaster.', 'リリーはめったにジェットコースターに乗らない。'],
    ['grass and glass', '草とガラス'],
    ['correct and collect', '正しいと集める'],
    ['world', '世界'],
    ['I really like the library.', '私は図書館が本当に好きです。'],
    ['Laura rarely rolls her Rs.', 'ローラはめったに巻き舌で R を発音しない。'],
  ],
  'TH の音': [
    ['think and sink', '考えると沈む'],
    ['three', '3'],
    ['thank you', 'ありがとう'],
    ['This is the thing.', 'これがそれだ。'],
    ['I think they thought about that.', '彼らはそれについて考えたと思う。'],
    ['mouth and mouse', '口とネズミ'],
    ['birthday', '誕生日'],
    ['weather and whether', '天気と〜かどうか'],
    ['My brother and father are both healthy.', '兄と父はどちらも健康です。'],
    ['Thirty-three thousand thoughts.', '3万3千の考え。'],
  ],
  'V と B / F と H': [
    ['very and berry', 'とても と ベリー'],
    ['vote and boat', '投票とボート'],
    ['vest and best', 'ベストと最高'],
    ['I love my favorite video.', 'お気に入りの動画が大好き。'],
    ['fan and hand', '扇風機と手'],
    ['food and hood', '食べ物とフード'],
    ['coffee', 'コーヒー'],
    ['Five fine fresh fish.', '5匹の立派な新鮮な魚。'],
  ],
  '母音（長い・短い）': [
    ['ship and sheep', '船と羊'],
    ['live and leave', '住むと去る'],
    ['full and fool', 'いっぱいと愚か者'],
    ['hat and hot and hut', '帽子と熱いと小屋'],
    ['walk and work', '歩くと働く'],
    ['bird', '鳥'],
    ['I want to leave, not live here.', 'ここに住むのではなく、去りたい。'],
    ['The cat sat on the mat.', '猫がマットに座った。'],
  ],
  'つなげて話す': [
    ['Check it out.', 'チェックしてみて。'],
    ['Pick it up.', '拾って。'],
    ['What do you want to do?', '何がしたい？'],
    ['I got to go.', 'もう行かなきゃ。'],
    ['Did you eat yet?', 'もうご飯食べた？'],
    ['Let me know.', '教えてね。'],
    ["I'm going to get a cup of coffee.", 'コーヒーを買ってくるよ。'],
    ['Not at all.', 'どういたしまして／全然。'],
    ['Could you give it to me?', 'それを私にくれますか？'],
  ],
  '早口ことば': [
    ['She sells seashells by the seashore.', '彼女は海辺で貝殻を売る。'],
    ['Red lorry, yellow lorry.', '赤いトラック、黄色いトラック。'],
    ['How can a clam cram in a clean cream can?', 'ハマグリがどうやってきれいなクリーム缶に詰まるの？'],
    ['Peter Piper picked a peck of pickled peppers.', 'ピーター・パイパーは漬けたトウガラシを1ペック摘んだ。'],
    ['How much wood would a woodchuck chuck if a woodchuck could chuck wood?', 'ウッドチャックが木を投げられたら、どれだけ投げるだろう？'],
    ['I scream, you scream, we all scream for ice cream.', 'みんなでアイスクリームを叫ぼう。'],
    ['Fuzzy Wuzzy was a bear.', 'ファジー・ワジーはクマだった。'],
    ['A big black bug bit a big black bear.', '大きな黒い虫が大きな黒いクマを噛んだ。'],
    ['Six slippery snails slid slowly seaward.', '6匹のぬるぬるしたカタツムリがゆっくり海へ滑っていった。'],
    ['Eleven benevolent elephants.', '11頭の優しいゾウ。'],
  ],
};

// 単語帳 [英語, 日本語, 例文]
const VOCAB = {
  '日常生活': [
    ['appointment', '予約・約束', 'I have a dentist appointment tomorrow.'],
    ['errand', '用事・お使い', 'I need to run some errands this afternoon.'],
    ['laundry', '洗濯物', 'I do the laundry on Sundays.'],
    ['commute', '通勤する', 'I commute to work by train.'],
    ['neighbor', '近所の人', 'My neighbor has a cute dog.'],
    ['grocery', '食料品', 'I went grocery shopping after work.'],
    ['chore', '家事・雑用', 'Washing dishes is my least favorite chore.'],
    ['schedule', '予定', 'My schedule is full this week.'],
    ['weekday', '平日', 'I get up at six on weekdays.'],
    ['rent', '家賃', 'The rent here is very expensive.'],
    ['garbage', 'ごみ', 'Can you take out the garbage?'],
    ['umbrella', '傘', "Don't forget your umbrella."],
    ['alarm', '目覚まし', 'I set my alarm for 6:30.'],
    ['nap', '昼寝', 'I took a short nap after lunch.'],
    ['habit', '習慣', 'Reading before bed is a good habit.'],
  ],
  '食べ物・料理': [
    ['ingredient', '材料', 'What are the ingredients for this soup?'],
    ['recipe', 'レシピ', 'Can you share the recipe?'],
    ['spicy', '辛い', 'Is this dish spicy?'],
    ['bitter', '苦い', 'This coffee is too bitter.'],
    ['sour', '酸っぱい', 'Lemons are sour.'],
    ['delicious', 'とてもおいしい', 'This cake is delicious!'],
    ['leftovers', '残り物', "Let's eat the leftovers for lunch."],
    ['vegetarian', '菜食主義者', 'Do you have vegetarian options?'],
    ['dessert', 'デザート', 'Do you have room for dessert?'],
    ['appetizer', '前菜', "Let's order an appetizer to share."],
    ['boil', 'ゆでる', 'Boil the eggs for ten minutes.'],
    ['fry', '揚げる・炒める', 'Fry the onions until golden.'],
    ['bake', '(オーブンで)焼く', 'I baked some cookies.'],
    ['raw', '生の', 'Can you eat raw fish?'],
    ['portion', '一人前の量', 'The portions here are huge.'],
  ],
  '旅行': [
    ['departure', '出発', 'The departure time is 9 a.m.'],
    ['arrival', '到着', 'Check the arrival gate on the screen.'],
    ['luggage', '荷物', 'I have two pieces of luggage.'],
    ['destination', '目的地', 'Our final destination is Paris.'],
    ['itinerary', '旅程', "Here's our itinerary for the trip."],
    ['aisle seat', '通路側の席', "I'd like an aisle seat, please."],
    ['boarding pass', '搭乗券', 'Please show your boarding pass.'],
    ['currency', '通貨', 'What currency do they use there?'],
    ['souvenir', 'お土産', 'I bought some souvenirs for my family.'],
    ['sightseeing', '観光', 'We went sightseeing in Kyoto.'],
    ['delay', '遅延', 'The flight has a two-hour delay.'],
    ['customs', '税関', 'We went through customs quickly.'],
    ['round trip', '往復', 'A round trip ticket, please.'],
    ['landmark', '名所・目印', 'The tower is a famous landmark.'],
    ['accommodation', '宿泊施設', 'We booked our accommodation online.'],
  ],
  '仕事・ビジネス': [
    ['deadline', '締め切り', 'The deadline is next Friday.'],
    ['colleague', '同僚', 'My colleague helped me with the report.'],
    ['agenda', '議題', "Let's go over today's agenda."],
    ['proposal', '提案(書)', 'I sent the proposal to the client.'],
    ['budget', '予算', "We're over budget this month."],
    ['negotiate', '交渉する', 'We need to negotiate the price.'],
    ['attach', '添付する', 'I attached the file to the email.'],
    ['postpone', '延期する', "Let's postpone the meeting to Monday."],
    ['client', '顧客', 'I have a meeting with a client.'],
    ['promotion', '昇進', 'She got a promotion last month.'],
    ['résumé', '履歴書', 'Please send us your résumé.'],
    ['revenue', '収益', 'Our revenue increased by 10%.'],
    ['confirm', '確認する', 'Could you confirm the date?'],
    ['in charge of', '〜を担当して', "I'm in charge of marketing."],
    ['follow up', 'フォローする・追って連絡する', "I'll follow up with an email."],
  ],
  '気持ち・性格': [
    ['excited', 'わくわくした', "I'm so excited about the trip!"],
    ['nervous', '緊張した', 'I was nervous before the interview.'],
    ['embarrassed', '恥ずかしい', 'I felt embarrassed when I fell.'],
    ['relieved', 'ほっとした', "I'm relieved that you're safe."],
    ['disappointed', 'がっかりした', 'I was disappointed with the movie.'],
    ['frustrated', 'イライラした', "I'm frustrated with this computer."],
    ['confident', '自信がある', "She's confident in her English."],
    ['grateful', '感謝している', "I'm grateful for your help."],
    ['exhausted', 'へとへとの', "I'm exhausted after work."],
    ['curious', '好奇心旺盛な', 'Kids are curious about everything.'],
    ['generous', '気前がいい', 'He is very generous with his time.'],
    ['shy', '内気な', 'I was shy when I was a child.'],
    ['outgoing', '社交的な', 'My sister is very outgoing.'],
    ['patient', '我慢強い', 'Thank you for being so patient.'],
    ['stubborn', '頑固な', 'My dad can be stubborn.'],
  ],
  '基本動詞': [
    ['borrow', '借りる', 'Can I borrow your pen?'],
    ['lend', '貸す', 'Could you lend me some money?'],
    ['explain', '説明する', 'Could you explain that again?'],
    ['recommend', '勧める', 'Can you recommend a good book?'],
    ['remind', '思い出させる', 'Please remind me tomorrow.'],
    ['suggest', '提案する', 'I suggest we take a break.'],
    ['decide', '決める', "I can't decide what to eat."],
    ['prefer', '〜のほうを好む', 'I prefer tea to coffee.'],
    ['forget', '忘れる', "Don't forget to call me."],
    ['improve', '上達する・改善する', 'I want to improve my English.'],
    ['share', '共有する', 'Can I share my screen?'],
    ['mention', '言及する', 'He mentioned your name.'],
    ['realize', '気づく', 'I realized I left my phone at home.'],
    ['expect', '予期する', "I didn't expect to see you here."],
    ['apologize', '謝る', 'I apologize for being late.'],
  ],
  'よく使う形容詞': [
    ['available', '空いている・利用できる', 'Are you available on Friday?'],
    ['convenient', '便利な・都合がいい', 'What time is convenient for you?'],
    ['crowded', '混んでいる', 'The train was really crowded.'],
    ['expensive', '高い(値段)', 'This bag is too expensive.'],
    ['reasonable', '手頃な', 'The prices are reasonable.'],
    ['comfortable', '快適な', 'This chair is very comfortable.'],
    ['familiar', 'よく知っている', 'Are you familiar with this area?'],
    ['necessary', '必要な', "It's not necessary to bring anything."],
    ['awesome', 'すごくいい', 'The concert was awesome!'],
    ['terrible', 'ひどい', 'The weather was terrible.'],
    ['upset', '動揺した・怒った', 'Why are you upset?'],
    ['quiet', '静かな', "Let's go somewhere quiet."],
    ['ordinary', '普通の', 'It was just an ordinary day.'],
    ['complicated', '複雑な', "It's a little complicated."],
    ['obvious', '明らかな', 'The answer is obvious.'],
  ],
  '句動詞': [
    ['pick up', '拾う・迎えに行く', "I'll pick you up at seven."],
    ['look forward to', '〜を楽しみにする', "I'm looking forward to seeing you."],
    ['figure out', '理解する・解決する', "I can't figure out this problem."],
    ['run out of', '〜を切らす', "We've run out of milk."],
    ['give up', '諦める', "Don't give up!"],
    ['find out', '知る・調べる', 'I found out the truth.'],
    ['show up', '現れる', "He didn't show up to the party."],
    ['put off', '延期する', "Don't put off your homework."],
    ['get along with', '〜と仲良くやる', 'I get along with my coworkers.'],
    ['come up with', '思いつく', 'She came up with a great idea.'],
    ['check out', '調べる・チェックアウトする', 'Check out this video!'],
    ['turn down', '断る・音量を下げる', 'He turned down the offer.'],
    ['hang out', 'ぶらぶら遊ぶ', "Let's hang out this weekend."],
    ['look up', '(辞書などで)調べる', 'I looked up the word online.'],
    ['take care of', '世話をする', 'Who takes care of your cat?'],
  ],
};

// 単語帳の追加分（既存カテゴリには追記、新しいカテゴリは追加）
Object.entries({
  '日常生活': [
    ['wake up', '目を覚ます', 'I usually wake up at seven.'],
    ['oversleep', '寝坊する', 'I overslept and missed the bus.'],
    ['tidy up', '片付ける', 'I need to tidy up my room.'],
    ['vacuum', '掃除機をかける', 'I vacuum the floor every weekend.'],
    ['iron', 'アイロンをかける', 'I have to iron my shirt.'],
    ['recycle', 'リサイクルする', 'We recycle bottles and cans.'],
    ['package', '小包', 'A package arrived for you.'],
    ['bill', '請求書・紙幣', 'I paid the electricity bill.'],
    ['routine', '日課', 'Jogging is part of my morning routine.'],
    ['day off', '休みの日', 'Tomorrow is my day off.'],
  ],
  '食べ物・料理': [
    ['flavor', '風味・味', 'This ice cream has a nice flavor.'],
    ['salty', 'しょっぱい', 'The soup is a little salty.'],
    ['greasy', '脂っこい', 'I don’t like greasy food.'],
    ['chop', '刻む', 'Chop the carrots into small pieces.'],
    ['stir', 'かき混ぜる', 'Stir the sauce slowly.'],
    ['grill', '網焼きにする', "Let's grill some fish."],
    ['homemade', '手作りの', 'This bread is homemade.'],
    ['takeout', '持ち帰りの料理', "Let's get takeout tonight."],
    ['cutlery', 'ナイフ・フォーク類', 'Could we have some more cutlery?'],
    ['full', 'お腹いっぱい', "I'm full. I can't eat any more."],
  ],
  '旅行': [
    ['passport', 'パスポート', "Don't forget your passport."],
    ['reservation', '予約', 'I have a reservation under Tanaka.'],
    ['check in', 'チェックインする', 'What time can we check in?'],
    ['check-out', 'チェックアウト', 'Check-out is at 11 a.m.'],
    ['one-way', '片道の', 'A one-way ticket to London, please.'],
    ['window seat', '窓側の席', 'Can I have a window seat?'],
    ['baggage claim', '手荷物受取所', 'Where is the baggage claim?'],
    ['jet lag', '時差ぼけ', "I'm still suffering from jet lag."],
    ['tourist', '観光客', 'This area is full of tourists.'],
    ['guidebook', 'ガイドブック', 'I read about it in my guidebook.'],
  ],
  '仕事・ビジネス': [
    ['meeting', '会議', "I'm in a meeting until three."],
    ['task', '業務・作業', 'I have a lot of tasks today.'],
    ['priority', '優先事項', "This is our top priority."],
    ['feedback', '意見・感想', 'Thanks for your feedback.'],
    ['estimate', '見積もり', 'Could you send us an estimate?'],
    ['invoice', '請求書', "I'll send you the invoice today."],
    ['contract', '契約', 'We signed the contract yesterday.'],
    ['overtime', '残業', 'I worked overtime last night.'],
    ['remote work', 'リモートワーク', 'I do remote work twice a week.'],
    ['business trip', '出張', "I'm going on a business trip to Osaka."],
  ],
  '気持ち・性格': [
    ['annoyed', 'イライラした', "I'm annoyed by the noise."],
    ['lonely', 'さびしい', 'I felt lonely when I lived abroad.'],
    ['proud', '誇りに思う', "I'm proud of you."],
    ['jealous', 'うらやましい・嫉妬した', "I'm so jealous of your trip!"],
    ['anxious', '不安な', "I'm anxious about the test."],
    ['satisfied', '満足した', 'Are you satisfied with the result?'],
    ['honest', '正直な', 'To be honest, I don’t like it.'],
    ['friendly', '人懐っこい', 'The staff were very friendly.'],
    ['lazy', '怠けた', 'I feel lazy today.'],
    ['reliable', '頼りになる', 'She is a reliable coworker.'],
  ],
  '基本動詞': [
    ['arrive', '到着する', 'What time did you arrive?'],
    ['bring', '持ってくる', "Don't forget to bring your ID."],
    ['change', '変える・着替える', 'Can I change my order?'],
    ['finish', '終える', 'I finished my homework.'],
    ['hope', '望む', 'I hope you feel better soon.'],
    ['keep', '保つ・取っておく', 'Keep the change.'],
    ['miss', '逃す・恋しく思う', 'I missed the last train.'],
    ['order', '注文する', 'Are you ready to order?'],
    ['prepare', '準備する', 'I need to prepare for the meeting.'],
    ['reply', '返信する', 'Sorry for the late reply.'],
  ],
  'よく使う形容詞': [
    ['busy', '忙しい', "I've been really busy lately."],
    ['free', '暇な・無料の', 'Are you free tonight?'],
    ['easy', '簡単な', 'This recipe is really easy.'],
    ['difficult', '難しい', 'English pronunciation is difficult.'],
    ['important', '重要な', 'This is very important.'],
    ['possible', '可能な', 'Is it possible to change the date?'],
    ['popular', '人気のある', 'This restaurant is very popular.'],
    ['empty', '空の', 'The bottle is empty.'],
    ['safe', '安全な', 'Is this area safe at night?'],
    ['similar', '似ている', 'Our ideas are similar.'],
  ],
  '句動詞': [
    ['set up', '設定する・準備する', "I'll set up the meeting."],
    ['go over', '見直す・確認する', "Let's go over the plan again."],
    ['run into', '偶然会う', 'I ran into an old friend.'],
    ['catch up', '追いつく・近況を話す', "Let's catch up over coffee."],
    ['calm down', '落ち着く', 'Calm down and take a deep breath.'],
    ['fill out', '(書類に)記入する', 'Please fill out this form.'],
    ['get over', '(病気・失恋から)立ち直る', "I finally got over my cold."],
    ['work out', '運動する・うまくいく', 'I work out three times a week.'],
    ['drop by', 'ちょっと立ち寄る', 'Drop by anytime.'],
    ['sign up', '申し込む・登録する', 'I signed up for an English class.'],
  ],
  '家・住まい': [
    ['apartment', 'アパート・マンション', 'I live in a small apartment.'],
    ['landlord', '大家', 'I called my landlord about the leak.'],
    ['furniture', '家具', 'We bought some new furniture.'],
    ['kitchen', '台所', 'The kitchen is next to the living room.'],
    ['bathroom', '浴室・トイレ', 'Where is the bathroom?'],
    ['bedroom', '寝室', 'This apartment has two bedrooms.'],
    ['balcony', 'バルコニー', 'I dry my laundry on the balcony.'],
    ['closet', 'クローゼット', 'Put your coat in the closet.'],
    ['drawer', '引き出し', 'The scissors are in the top drawer.'],
    ['shelf', '棚', 'Put the book back on the shelf.'],
    ['sink', '流し台', 'The dishes are in the sink.'],
    ['fridge', '冷蔵庫', 'There is some juice in the fridge.'],
    ['microwave', '電子レンジ', 'Heat it up in the microwave.'],
    ['move', '引っ越す', 'We moved to a new house last year.'],
    ['utilities', '光熱費', 'Are utilities included in the rent?'],
  ],
  '体・健康': [
    ['headache', '頭痛', 'I have a terrible headache.'],
    ['stomachache', '腹痛', 'I have a stomachache.'],
    ['sore throat', 'のどの痛み', 'I have a sore throat.'],
    ['fever', '熱', 'She has a high fever.'],
    ['cough', '咳', "I can't stop coughing."],
    ['runny nose', '鼻水', 'I have a runny nose.'],
    ['allergy', 'アレルギー', 'I have a pollen allergy.'],
    ['medicine', '薬', 'Take this medicine after meals.'],
    ['prescription', '処方箋', 'You need a prescription for this.'],
    ['injury', 'けが', 'He had a knee injury.'],
    ['dizzy', 'めまいがする', 'I feel dizzy.'],
    ['sleepy', '眠い', "I'm so sleepy today."],
    ['diet', '食事制限・ダイエット', "I'm on a diet."],
    ['exercise', '運動', 'I try to get some exercise every day.'],
    ['recover', '回復する', 'I hope you recover soon.'],
  ],
  '天気・自然': [
    ['sunny', '晴れた', "It's sunny today."],
    ['cloudy', '曇った', 'It was cloudy all day.'],
    ['humid', '蒸し暑い', "It's so humid in Tokyo in summer."],
    ['chilly', '肌寒い', "It's a little chilly this morning."],
    ['freezing', '凍えるほど寒い', "It's freezing outside!"],
    ['forecast', '天気予報', 'The forecast says it will rain.'],
    ['shower', 'にわか雨', 'There may be showers this afternoon.'],
    ['thunder', '雷', 'Did you hear the thunder?'],
    ['typhoon', '台風', 'A typhoon is coming this weekend.'],
    ['earthquake', '地震', 'There was a small earthquake last night.'],
    ['temperature', '気温', 'The temperature is 30 degrees.'],
    ['season', '季節', 'Which season do you like best?'],
    ['sunset', '夕日', 'The sunset was beautiful.'],
    ['view', '眺め', 'What a great view!'],
    ['countryside', '田舎', 'I grew up in the countryside.'],
  ],
  '買い物・お金': [
    ['price', '値段', 'The price is too high.'],
    ['cheap', '安い', 'This shop is really cheap.'],
    ['sale', 'セール', 'Everything is 30% off during the sale.'],
    ['receipt', 'レシート', 'Do you need a receipt?'],
    ['refund', '返金', "I'd like a refund, please."],
    ['exchange', '交換する', 'Can I exchange this for a larger size?'],
    ['cash', '現金', 'Do you accept cash?'],
    ['coin', '硬貨', 'I have a lot of coins in my wallet.'],
    ['cashier', 'レジ係', 'Please pay at the cashier.'],
    ['in stock', '在庫がある', 'Is this item in stock?'],
    ['sold out', '売り切れ', 'Sorry, it’s sold out.'],
    ['afford', '(金銭的に)余裕がある', "I can't afford a new car."],
    ['save money', 'お金を貯める', "I'm trying to save money."],
    ['tax', '税金', 'Is tax included?'],
    ['tip', 'チップ', 'How much should I tip?'],
  ],
  '趣味・娯楽': [
    ['hobby', '趣味', 'What are your hobbies?'],
    ['hiking', 'ハイキング', 'I go hiking on weekends.'],
    ['camping', 'キャンプ', "We're going camping this summer."],
    ['concert', 'コンサート', 'I went to a concert last night.'],
    ['museum', '博物館・美術館', "Let's visit the museum."],
    ['episode', '(ドラマの)1話', 'I watched three episodes last night.'],
    ['series', 'シリーズ・連続ドラマ', 'Have you seen this series?'],
    ['novel', '小説', "I'm reading a mystery novel."],
    ['instrument', '楽器', 'Do you play any instruments?'],
    ['photography', '写真撮影', "I'm into photography these days."],
    ['board game', 'ボードゲーム', "Let's play a board game."],
    ['gym', 'ジム', 'I go to the gym after work.'],
    ['team', 'チーム', 'Which team do you support?'],
    ['ticket', 'チケット', 'I got two tickets for the game.'],
    ['fan', 'ファン', "I'm a big fan of that singer."],
  ],
  '学校・勉強': [
    ['major', '専攻', 'My major was economics.'],
    ['degree', '学位', 'She has a degree in law.'],
    ['graduate', '卒業する', 'I graduated from college in 2015.'],
    ['lecture', '講義', 'The lecture starts at nine.'],
    ['assignment', '課題', 'I have an assignment due tomorrow.'],
    ['exam', '試験', 'I passed the exam!'],
    ['grade', '成績・学年', 'I got a good grade in math.'],
    ['vocabulary', '語彙', 'I want to build my vocabulary.'],
    ['grammar', '文法', 'English grammar is not so hard.'],
    ['pronunciation', '発音', 'Your pronunciation is very good.'],
    ['fluent', '流暢な', 'She is fluent in three languages.'],
    ['memorize', '暗記する', 'I memorize ten new words a day.'],
    ['review', '復習する', "Let's review what we learned."],
    ['practice', '練習する', 'Practice makes perfect.'],
    ['scholarship', '奨学金', 'He studied abroad on a scholarship.'],
  ],
  '時間・頻度': [
    ['always', 'いつも', 'I always drink coffee in the morning.'],
    ['usually', 'たいてい', 'I usually walk to work.'],
    ['often', 'よく', 'We often eat out on Fridays.'],
    ['sometimes', 'ときどき', 'I sometimes cook dinner.'],
    ['rarely', 'めったに〜ない', 'I rarely watch TV.'],
    ['never', '一度も〜ない', "I've never been to Europe."],
    ['recently', '最近', 'Have you seen any good movies recently?'],
    ['lately', '最近(継続)', "I've been tired lately."],
    ['already', 'もう・すでに', "I've already eaten."],
    ['yet', 'まだ・もう(疑問/否定)', "I haven't finished yet."],
    ['still', 'まだ(続いている)', "It's still raining."],
    ['soon', 'もうすぐ', "I'll be there soon."],
    ['eventually', '結局・最終的に', 'Eventually, we found the hotel.'],
    ['on time', '時間どおりに', 'The train arrived on time.'],
    ['in advance', '前もって', 'Please book in advance.'],
  ],
  '会話の便利表現': [
    ['by the way', 'ところで', 'By the way, how was your trip?'],
    ['actually', '実は', "Actually, I've never been there."],
    ['anyway', 'とにかく・それはさておき', 'Anyway, let’s get started.'],
    ['to be honest', '正直に言うと', 'To be honest, I was a little nervous.'],
    ['it depends', '場合によるね', "It depends on the weather."],
    ['no big deal', '大したことじゃない', "Don't worry, it's no big deal."],
    ['makes sense', 'なるほど・筋が通る', 'Oh, that makes sense now.'],
    ['sounds good', 'いいね', "Pizza tonight? Sounds good!"],
    ['for sure', '確かに・もちろん', "I'll be there for sure."],
    ['kind of', 'ちょっと・なんとなく', "I'm kind of tired."],
    ['you know', 'ほら・〜でしょ', "It's, you know, the place near the station."],
    ['what do you mean', 'どういう意味？', 'What do you mean by that?'],
    ['never mind', '気にしないで', 'Never mind, it’s not important.'],
    ['I mean', 'つまり・いや', 'I mean, it was okay, but not great.'],
    ['just in case', '念のため', 'Take an umbrella just in case.'],
  ],
}).forEach(([cat, list]) => { VOCAB[cat] = [...(VOCAB[cat] || []), ...list]; });
