// 会話練習シナリオ
// turns: 相手(ai)のセリフと、ユーザーが返す模範解答(answers)。hint は日本語の言いたいこと。
const SCENARIOS = [
  {
    id: 'intro', emoji: '👋', name: '自己紹介', desc: '初対面の人と話す',
    turns: [
      { ai: "Hi there! I'm Emma. What's your name?", ja: 'こんにちは！エマです。お名前は？',
        hint: '自分の名前を伝えよう', answers: ["Hi Emma, my name is Ken.", "Nice to meet you, I'm Ken.", "Hello, I'm Ken. Nice to meet you."] },
      { ai: "Nice to meet you! Where are you from?", ja: 'はじめまして！どちらの出身ですか？',
        hint: '日本の出身だと伝えよう', answers: ["I'm from Japan.", "I'm from Tokyo, Japan.", "I come from Japan."] },
      { ai: "Oh, cool! What do you do?", ja: 'へえ、いいね！お仕事は何をしていますか？',
        hint: '仕事を説明しよう（例：エンジニア）', answers: ["I work as an engineer.", "I'm a software engineer.", "I'm an office worker."] },
      { ai: "That sounds interesting. What do you like to do in your free time?", ja: '面白そう。暇なときは何をするのが好き？',
        hint: '趣味を伝えよう', answers: ["I like watching movies.", "I enjoy reading books and playing tennis.", "I like to travel in my free time."] },
      { ai: "Great! It was nice talking to you.", ja: 'いいね！話せてよかったです。',
        hint: 'こちらこそ、と返そう', answers: ["It was nice talking to you too.", "Nice talking to you too. See you!", "Same here. Have a nice day!"] },
    ],
  },
  {
    id: 'restaurant', emoji: '🍽️', name: 'レストラン', desc: '注文・会計をする',
    turns: [
      { ai: "Good evening! How many people are in your party?", ja: 'こんばんは！何名様ですか？',
        hint: '2人だと伝えよう', answers: ["Two, please.", "A table for two, please.", "There are two of us."] },
      { ai: "Right this way. Can I get you something to drink?", ja: 'こちらへどうぞ。お飲み物はいかがですか？',
        hint: '水をお願いしよう', answers: ["Just water, please.", "Can I have some water, please?", "I'll have a glass of water, please."] },
      { ai: "Are you ready to order?", ja: 'ご注文はお決まりですか？',
        hint: 'ハンバーガーを注文しよう', answers: ["Yes, I'd like the hamburger, please.", "I'll have the hamburger.", "Can I get the hamburger, please?"] },
      { ai: "Would you like fries or a salad with that?", ja: 'ポテトとサラダ、どちらになさいますか？',
        hint: 'サラダを選ぼう', answers: ["Salad, please.", "I'll have a salad, please.", "A salad would be great."] },
      { ai: "How is everything tasting?", ja: 'お味はいかがですか？',
        hint: 'とてもおいしいと伝えよう', answers: ["Everything is delicious, thank you.", "It's really good, thanks.", "It's great, thank you."] },
      { ai: "Can I get you anything else?", ja: '他に何かお持ちしましょうか？',
        hint: 'お会計をお願いしよう', answers: ["Could we get the check, please?", "Just the check, please.", "Can I have the bill, please?"] },
    ],
  },
  {
    id: 'airport', emoji: '✈️', name: '空港・入国審査', desc: 'チェックインと入国審査',
    turns: [
      { ai: "May I see your passport, please?", ja: 'パスポートを拝見できますか？',
        hint: 'はい、どうぞと渡そう', answers: ["Here you are.", "Sure, here it is.", "Here is my passport."] },
      { ai: "What's the purpose of your visit?", ja: '訪問の目的は何ですか？',
        hint: '観光だと伝えよう', answers: ["Sightseeing.", "I'm here for sightseeing.", "I'm here on vacation."] },
      { ai: "How long will you be staying?", ja: 'どのくらい滞在しますか？',
        hint: '1週間だと伝えよう', answers: ["For one week.", "I'll be staying for a week.", "About one week."] },
      { ai: "Where will you be staying?", ja: 'どこに滞在しますか？',
        hint: 'ヒルトンホテルに泊まると伝えよう', answers: ["At the Hilton Hotel.", "I'll be staying at the Hilton Hotel.", "I'm staying at the Hilton."] },
      { ai: "Do you have anything to declare?", ja: '申告するものはありますか？',
        hint: 'ありません、と答えよう', answers: ["No, nothing to declare.", "No, I don't.", "No, I have nothing to declare."] },
    ],
  },
  {
    id: 'hotel', emoji: '🏨', name: 'ホテル', desc: 'チェックインと要望',
    turns: [
      { ai: "Welcome! How can I help you?", ja: 'いらっしゃいませ！ご用件は？',
        hint: 'チェックインしたいと伝えよう', answers: ["I'd like to check in, please.", "I have a reservation. I'd like to check in.", "Check in, please."] },
      { ai: "May I have your name, please?", ja: 'お名前をいただけますか？',
        hint: '名前を伝えよう', answers: ["It's Ken Tanaka.", "My name is Ken Tanaka.", "The reservation is under Tanaka."] },
      { ai: "Thank you. You're in room 512. Is there anything else?", ja: 'ありがとうございます。512号室です。他に何か？',
        hint: '朝食の時間を聞こう', answers: ["What time is breakfast?", "What time is breakfast served?", "When is breakfast?"] },
      { ai: "Breakfast is from 7 to 10 a.m. on the second floor.", ja: '朝食は2階で7時から10時です。',
        hint: 'Wi-Fiのパスワードを聞こう', answers: ["What's the Wi-Fi password?", "Could you tell me the Wi-Fi password?", "Can I have the Wi-Fi password, please?"] },
      { ai: "It's on your key card holder. Enjoy your stay!", ja: 'カードキーのケースに書いてあります。ごゆっくりどうぞ！',
        hint: 'お礼を言おう', answers: ["Thank you very much.", "Thanks a lot.", "Thank you, have a nice day."] },
    ],
  },
  {
    id: 'shopping', emoji: '🛍️', name: '買い物', desc: 'サイズや値段を聞く',
    turns: [
      { ai: "Hi! Can I help you find something?", ja: 'こんにちは！何かお探しですか？',
        hint: '見ているだけです、と伝えよう', answers: ["I'm just looking, thanks.", "Just looking, thank you.", "No thanks, I'm just browsing."] },
      { ai: "Sure, let me know if you need anything.", ja: 'はい、何かあればお声がけください。',
        hint: 'このシャツのMサイズはあるか聞こう', answers: ["Do you have this shirt in a medium?", "Do you have this in medium?", "Is there a medium size for this shirt?"] },
      { ai: "Yes, here you go. Would you like to try it on?", ja: 'はい、どうぞ。試着されますか？',
        hint: '試着室の場所を聞こう', answers: ["Yes, where is the fitting room?", "Yes please. Where are the fitting rooms?", "Sure, where can I try it on?"] },
      { ai: "How does it fit?", ja: 'サイズはいかがですか？',
        hint: 'ぴったりです、いくらですか？', answers: ["It fits perfectly. How much is it?", "It's perfect. How much is this?", "It fits well. How much does it cost?"] },
      { ai: "It's 35 dollars. How would you like to pay?", ja: '35ドルです。お支払いはどうされますか？',
        hint: 'カードで払おう', answers: ["By credit card, please.", "Can I pay by card?", "I'll pay with my credit card."] },
    ],
  },
  {
    id: 'directions', emoji: '🗺️', name: '道を尋ねる', desc: '駅や場所への行き方',
    turns: [
      { ai: "Hi, you look lost. Can I help you?", ja: '迷っているようですね。お手伝いしましょうか？',
        hint: '駅への行き方を聞こう', answers: ["Yes, how do I get to the station?", "Could you tell me the way to the station?", "Excuse me, where is the train station?"] },
      { ai: "Go straight for two blocks and turn left.", ja: '2ブロックまっすぐ行って左に曲がってください。',
        hint: '歩いてどのくらいか聞こう', answers: ["How long does it take on foot?", "How long will it take to walk there?", "Is it far from here?"] },
      { ai: "About ten minutes on foot.", ja: '歩いて約10分です。',
        hint: '近くにコンビニがあるかも聞こう', answers: ["Is there a convenience store nearby?", "Is there a convenience store near here?", "Where is the nearest convenience store?"] },
      { ai: "Yes, there's one right next to the station.", ja: 'はい、駅のすぐ隣にありますよ。',
        hint: '丁寧にお礼を言おう', answers: ["Thank you so much for your help.", "Thanks, you've been very helpful.", "Thank you very much."] },
    ],
  },
  {
    id: 'cafe', emoji: '☕', name: 'カフェ', desc: 'コーヒーを注文する',
    turns: [
      { ai: "Hi! What can I get for you?", ja: 'こんにちは！ご注文は？',
        hint: 'ラテのMサイズを注文しよう', answers: ["Can I get a medium latte, please?", "I'd like a medium latte, please.", "A medium latte, please."] },
      { ai: "Hot or iced?", ja: 'ホットとアイス、どちらにしますか？',
        hint: 'アイスで', answers: ["Iced, please.", "I'll have it iced.", "Iced, please. Thank you."] },
      { ai: "For here or to go?", ja: '店内でお召し上がりですか、お持ち帰りですか？',
        hint: '持ち帰りで', answers: ["To go, please.", "It's to go.", "I'll take it to go."] },
      { ai: "Can I get a name for the order?", ja: 'ご注文のお名前をいただけますか？',
        hint: '名前を伝えよう', answers: ["It's Ken.", "Ken, please.", "My name is Ken."] },
    ],
  },
  {
    id: 'doctor', emoji: '🏥', name: '病院・薬局', desc: '症状を伝える',
    turns: [
      { ai: "What seems to be the problem today?", ja: '今日はどうされましたか？',
        hint: '頭痛がすると伝えよう', answers: ["I have a headache.", "I've had a bad headache.", "My head hurts."] },
      { ai: "How long have you had it?", ja: 'いつからですか？',
        hint: '昨日からと伝えよう', answers: ["Since yesterday.", "I've had it since yesterday.", "It started yesterday."] },
      { ai: "Do you have a fever?", ja: '熱はありますか？',
        hint: '少し熱があると伝えよう', answers: ["Yes, I have a slight fever.", "I have a little fever.", "Yes, a little."] },
      { ai: "Are you allergic to any medicine?", ja: '薬のアレルギーはありますか？',
        hint: 'ありません', answers: ["No, I'm not allergic to anything.", "No, I don't have any allergies.", "No, I'm not."] },
    ],
  },
  {
    id: 'taxi', emoji: '🚕', name: 'タクシー', desc: '行き先を伝える',
    turns: [
      { ai: "Hi, where to?", ja: 'どちらまで？',
        hint: 'セントラル駅までお願いしよう', answers: ["To Central Station, please.", "Central Station, please.", "Could you take me to Central Station?"] },
      { ai: "Sure. Are you in a hurry?", ja: 'かしこまりました。お急ぎですか？',
        hint: '3時の電車に乗りたいと伝えよう', answers: ["Yes, I need to catch a train at three.", "Yes, my train leaves at three.", "A little. I have a train at three o'clock."] },
      { ai: "No problem. We should get there in about fifteen minutes.", ja: '大丈夫です。15分ほどで着くと思います。',
        hint: 'エアコンを弱めてもらえるか聞こう', answers: ["Could you turn down the air conditioner?", "Can you turn the AC down a little?", "Could you make it a little warmer, please?"] },
      { ai: "Here we are. That'll be eighteen dollars.", ja: '着きました。18ドルです。',
        hint: '20ドル渡して、お釣りはいらないと伝えよう', answers: ["Here's twenty. Keep the change.", "Here you go. Keep the change.", "Here is twenty dollars. Please keep the change."] },
      { ai: "Thank you! Have a safe trip.", ja: 'ありがとうございます！よい旅を。',
        hint: 'お礼を言おう', answers: ["Thank you. Have a nice day.", "Thanks, you too.", "Thank you very much."] },
    ],
  },
  {
    id: 'train', emoji: '🚆', name: '駅・電車', desc: '切符を買う・乗り換え',
    turns: [
      { ai: "Next, please. How can I help you?", ja: '次の方どうぞ。ご用件は？',
        hint: 'ボストンまでの往復切符を1枚買おう', answers: ["One round-trip ticket to Boston, please.", "I'd like a round-trip ticket to Boston.", "Can I get a return ticket to Boston?"] },
      { ai: "Sure. That's forty-five dollars. The next train leaves at 10:30.", ja: 'はい、45ドルです。次の電車は10時30分発です。',
        hint: '何番線から出るか聞こう', answers: ["Which platform does it leave from?", "What platform is it?", "Which track does the train leave from?"] },
      { ai: "Platform 4. It's down the stairs on your right.", ja: '4番線です。右手の階段を下りたところです。',
        hint: '乗り換えが必要か聞こう', answers: ["Do I need to change trains?", "Do I have to transfer?", "Is it a direct train?"] },
      { ai: "No, it's a direct train. It takes about two hours.", ja: 'いいえ、直通です。約2時間かかります。',
        hint: 'お礼を言おう', answers: ["Great, thank you.", "Thank you for your help.", "Perfect. Thanks a lot."] },
    ],
  },
  {
    id: 'phone', emoji: '📞', name: '電話で予約', desc: 'レストランを予約する',
    turns: [
      { ai: "Hello, Bella Italia. How may I help you?", ja: 'はい、ベラ・イタリアです。ご用件をどうぞ。',
        hint: '予約をしたいと伝えよう', answers: ["Hi, I'd like to make a reservation.", "I'd like to book a table, please.", "Hello, can I make a reservation?"] },
      { ai: "Of course. For what day and time?", ja: 'かしこまりました。何日の何時ですか？',
        hint: '今週の土曜の夜7時で', answers: ["This Saturday at 7 p.m.", "Saturday at seven, please.", "For this Saturday at seven in the evening."] },
      { ai: "And how many people?", ja: '何名様ですか？',
        hint: '4人です', answers: ["Four people.", "There will be four of us.", "A table for four, please."] },
      { ai: "Could I have your name and phone number?", ja: 'お名前とお電話番号をいただけますか？',
        hint: '名前と番号を伝えよう', answers: ["It's Ken Tanaka, and my number is 555-1234.", "My name is Tanaka. My number is 555-1234.", "Tanaka, 555-1234."] },
      { ai: "Great, you're all set. Is there anything else?", ja: 'ご予約完了です。他に何かございますか？',
        hint: '窓際の席をお願いできるか聞こう', answers: ["Could we have a table by the window?", "Is it possible to get a window seat?", "Can we sit by the window?"] },
    ],
  },
  {
    id: 'invite', emoji: '🎉', name: '友達を誘う', desc: '予定を立てる',
    turns: [
      { ai: "Hey! What are you up to this weekend?", ja: 'やあ！今週末は何するの？',
        hint: '特に予定はないと伝えよう', answers: ["Nothing special. How about you?", "I don't have any plans yet.", "Not much. What about you?"] },
      { ai: "I'm thinking of going to the beach. Want to come?", ja: 'ビーチに行こうと思ってるんだ。一緒に来る？',
        hint: 'ぜひ行きたい！', answers: ["Sure, I'd love to!", "That sounds great. Count me in!", "Yes, I'd love to come."] },
      { ai: "Awesome! How about Saturday morning?", ja: 'いいね！土曜の朝はどう？',
        hint: '何時に待ち合わせるか聞こう', answers: ["Sounds good. What time should we meet?", "Saturday works. What time?", "Great. Where and when should we meet?"] },
      { ai: "Let's meet at the station at nine.", ja: '9時に駅で待ち合わせよう。',
        hint: '何か持っていくものがあるか聞こう', answers: ["Okay. Should I bring anything?", "Got it. Do I need to bring anything?", "Sure. What should I bring?"] },
      { ai: "Just a towel and some sunscreen. See you then!", ja: 'タオルと日焼け止めだけでいいよ。じゃあね！',
        hint: '楽しみにしてる、と伝えよう', answers: ["I can't wait. See you!", "Looking forward to it. See you Saturday!", "Great, see you then!"] },
    ],
  },
  {
    id: 'meeting', emoji: '💼', name: '会議', desc: '仕事で意見を伝える',
    turns: [
      { ai: "Thanks for joining. Could you give us an update on the project?", ja: 'ご参加ありがとうございます。プロジェクトの進捗を教えてもらえますか？',
        hint: '予定通り進んでいると伝えよう', answers: ["Sure. The project is on schedule.", "We're on track with the project.", "Everything is going according to plan."] },
      { ai: "Great. Are there any issues we should know about?", ja: 'いいですね。知っておくべき問題はありますか？',
        hint: 'テストに少し時間がかかっていると伝えよう', answers: ["Testing is taking a little longer than expected.", "The testing phase is taking more time than we planned.", "We have a small delay in testing."] },
      { ai: "I see. What do you suggest?", ja: 'なるほど。どうしたらいいと思いますか？',
        hint: 'もう1人メンバーを追加したい', answers: ["I suggest adding one more person to the team.", "I think we need one more team member.", "Could we add another person to the team?"] },
      { ai: "That makes sense. Can you send me the details by Friday?", ja: 'なるほど。金曜日までに詳細を送ってもらえますか？',
        hint: 'もちろんです', answers: ["Of course. I'll send them by Friday.", "Sure, I'll email you the details by Friday.", "No problem. I'll send it by Friday."] },
    ],
  },
  {
    id: 'exchange', emoji: '💱', name: '両替・銀行', desc: 'お金を両替する',
    turns: [
      { ai: "Good morning. What can I do for you?", ja: 'おはようございます。ご用件は？',
        hint: '円をドルに両替したい', answers: ["I'd like to exchange yen for dollars.", "Can I change some yen into dollars?", "I want to exchange Japanese yen to US dollars."] },
      { ai: "Sure. How much would you like to exchange?", ja: 'かしこまりました。いくら両替しますか？',
        hint: '3万円です', answers: ["Thirty thousand yen, please.", "I'd like to exchange 30,000 yen.", "30,000 yen, please."] },
      { ai: "May I see your ID, please?", ja: '身分証を拝見できますか？',
        hint: 'パスポートを渡そう', answers: ["Here's my passport.", "Sure, here you are.", "Here is my passport."] },
      { ai: "Thank you. How would you like your bills?", ja: 'ありがとうございます。紙幣の内訳はどうしますか？',
        hint: '20ドル札でお願いしよう', answers: ["Twenties, please.", "In twenty-dollar bills, please.", "Could I have them in twenties?"] },
      { ai: "Here you go. Please check the amount.", ja: 'どうぞ。金額をご確認ください。',
        hint: '大丈夫です、ありがとう', answers: ["That's correct. Thank you.", "It's all there. Thanks.", "Everything looks fine. Thank you."] },
    ],
  },
  {
    id: 'lost', emoji: '🆘', name: 'トラブル・落とし物', desc: '困ったときに助けを求める',
    turns: [
      { ai: "Hello, this is the lost and found. How can I help?", ja: 'こちら遺失物取扱所です。どうしましたか？',
        hint: '財布をなくしたと伝えよう', answers: ["I lost my wallet.", "I think I lost my wallet.", "I can't find my wallet."] },
      { ai: "I'm sorry to hear that. Where did you last have it?", ja: 'それはお気の毒に。最後に持っていたのはどこですか？',
        hint: '電車の中だと思う', answers: ["I think I left it on the train.", "Probably on the train.", "I had it on the train."] },
      { ai: "Can you describe it?", ja: 'どんな財布か説明できますか？',
        hint: '黒い革の財布です', answers: ["It's a black leather wallet.", "It's black and made of leather.", "A small black leather wallet."] },
      { ai: "Let me check... Is this yours?", ja: '確認しますね…これですか？',
        hint: 'はい、それです！', answers: ["Yes, that's mine! Thank you so much!", "Yes, that's it!", "That's my wallet. Thank you!"] },
    ],
  },
  {
    id: 'homestay', emoji: '🏠', name: 'ホームステイ', desc: 'ホストファミリーと話す',
    turns: [
      { ai: "Welcome to our home! How was your flight?", ja: 'ようこそ我が家へ！フライトはどうだった？',
        hint: '長かったけど快適だった', answers: ["It was long, but comfortable.", "It was a long flight, but it was fine.", "Long, but I was able to sleep."] },
      { ai: "You must be tired. Are you hungry?", ja: '疲れたでしょう。お腹すいてる？',
        hint: '少しすいている', answers: ["Yes, a little.", "I'm a little hungry.", "Yes, I'm kind of hungry."] },
      { ai: "Great, dinner will be ready soon. Is there anything you can't eat?", ja: 'よかった、夕食はもうすぐできるよ。食べられないものはある？',
        hint: '何でも食べられる', answers: ["No, I can eat anything.", "I can eat everything.", "Nothing, I'm not picky."] },
      { ai: "Perfect. Please make yourself at home.", ja: 'よかった。くつろいでね。',
        hint: 'シャワーを使ってもいいか聞こう', answers: ["Thank you. May I take a shower?", "Can I use the shower?", "Is it okay if I take a shower?"] },
      { ai: "Of course! Towels are in the bathroom.", ja: 'もちろん！タオルはお風呂場にあるよ。',
        hint: '温かく迎えてくれてありがとう', answers: ["Thank you for having me.", "Thank you for welcoming me.", "Thanks for everything."] },
    ],
  },
  {
    id: 'movie', emoji: '🎬', name: '映画館', desc: 'チケットと売店',
    turns: [
      { ai: "Hi, which movie would you like to see?", ja: 'こんにちは、どの映画をご覧になりますか？',
        hint: '7時の回を大人2枚', answers: ["Two adults for the seven o'clock show, please.", "Two tickets for the 7 p.m. show, please.", "Two adult tickets for the seven o'clock, please."] },
      { ai: "Where would you like to sit?", ja: 'どの辺りの席がよろしいですか？',
        hint: '真ん中あたりで', answers: ["Somewhere in the middle, please.", "In the middle, please.", "Middle seats, if possible."] },
      { ai: "Here are your tickets. Would you like any snacks?", ja: 'チケットです。何か軽食はいかがですか？',
        hint: 'ポップコーンのLとコーラを2つ', answers: ["A large popcorn and two Cokes, please.", "Can I get a large popcorn and two Cokes?", "I'll have a large popcorn and two colas."] },
      { ai: "Salted or butter?", ja: '塩とバター、どちらにしますか？',
        hint: 'バターで', answers: ["Butter, please.", "I'll have butter.", "Butter, thanks."] },
    ],
  },
  {
    id: 'supermarket', emoji: '🛒', name: 'スーパー', desc: '売り場を探す・レジ',
    turns: [
      { ai: "Hi there. Can I help you find something?", ja: 'こんにちは。何かお探しですか？',
        hint: '牛乳はどこか聞こう', answers: ["Yes, where can I find the milk?", "Where is the milk?", "Excuse me, which aisle is the milk in?"] },
      { ai: "It's in aisle five, next to the eggs.", ja: '5番通路の卵の隣です。',
        hint: 'ありがとう', answers: ["Thank you.", "Thanks a lot.", "Great, thanks."] },
      { ai: "Next customer, please. Do you need a bag?", ja: '次のお客様どうぞ。袋はいりますか？',
        hint: 'いりません、エコバッグがある', answers: ["No, thanks. I have my own bag.", "No, I brought my own bag.", "I don't need one, thanks."] },
      { ai: "Your total is twelve fifty. Do you have a membership card?", ja: '合計12ドル50セントです。会員カードはお持ちですか？',
        hint: '持っていません', answers: ["No, I don't.", "No, I don't have one.", "Sorry, I don't have one."] },
    ],
  },
];

// 発音練習フレーズ
const PHRASES = {
  'あいさつ': [
    ['How are you doing?', '調子はどう？'],
    ["Nice to meet you.", 'はじめまして。'],
    ["Long time no see.", '久しぶり。'],
    ["Have a nice weekend.", '良い週末を。'],
    ["See you later.", 'また後でね。'],
    ["Thank you for your help.", '助けてくれてありがとう。'],
    ["What's up?", '最近どう？'],
    ["How have you been?", '元気にしてた？'],
    ["It was nice talking to you.", '話せてよかったです。'],
    ["Take care.", '気をつけてね。'],
    ["Sorry to keep you waiting.", 'お待たせしてすみません。'],
    ["Say hello to your family for me.", 'ご家族によろしく。'],
  ],
  'リアクション': [
    ["That sounds great!", 'それはいいね！'],
    ["No way!", 'まさか！'],
    ["I know what you mean.", 'わかるよ。'],
    ["That's too bad.", 'それは残念。'],
    ["Good for you!", 'よかったね！'],
    ["I couldn't agree more.", '大賛成です。'],
    ["Are you serious?", '本気で言ってるの？'],
    ["It's up to you.", 'あなたに任せるよ。'],
    ["No worries.", '気にしないで。'],
    ["I'm not sure about that.", 'それはどうかな。'],
  ],
  '旅行': [
    ["Where is the nearest station?", '最寄り駅はどこですか？'],
    ["How much is this?", 'これはいくらですか？'],
    ["Could you take a picture of us?", '写真を撮っていただけますか？'],
    ["I'd like to make a reservation.", '予約をしたいのですが。'],
    ["Can I pay by credit card?", 'クレジットカードで払えますか？'],
    ["Is this seat taken?", 'この席は空いていますか？'],
    ["What time does it open?", '何時に開きますか？'],
    ["Could you recommend a good restaurant?", 'おすすめのレストランはありますか？'],
    ["I'm looking for this address.", 'この住所を探しています。'],
    ["Can I get a map, please?", '地図をもらえますか？'],
    ["Where can I buy a ticket?", '切符はどこで買えますか？'],
  ],
  'レストラン・買い物': [
    ["Can I see the menu, please?", 'メニューを見せてもらえますか？'],
    ["What do you recommend?", 'おすすめは何ですか？'],
    ["I'll have the same.", '同じものをください。'],
    ["Could I get a refill?", 'おかわりをもらえますか？'],
    ["Can I get this to go?", 'これを持ち帰りにできますか？'],
    ["Can I try this on?", '試着してもいいですか？'],
    ["Do you have this in a smaller size?", 'これの小さいサイズはありますか？'],
    ["I'm just looking, thanks.", '見ているだけです。'],
    ["Could I get a receipt?", 'レシートをもらえますか？'],
    ["Is there a discount?", '割引はありますか？'],
  ],
  '仕事': [
    ["Let me check and get back to you.", '確認して折り返します。'],
    ["Could you send me the details?", '詳細を送っていただけますか？'],
    ["I'm afraid I can't make it.", '残念ながら行けそうにありません。'],
    ["Let's schedule a meeting.", 'ミーティングを設定しましょう。'],
    ["That makes sense.", 'なるほど、納得です。'],
    ["Could you say that again, please?", 'もう一度言っていただけますか？'],
    ["I'll keep you posted.", '随時お知らせします。'],
    ["What's the deadline?", '締め切りはいつですか？'],
    ["Let's move on to the next topic.", '次の議題に移りましょう。'],
    ["I'd like to share my screen.", '画面を共有したいです。'],
    ["Sorry, you're on mute.", 'すみません、ミュートになっていますよ。'],
    ["Thank you for your time today.", '本日はお時間をいただきありがとうございました。'],
  ],
  '電話': [
    ["May I ask who's calling?", 'どちら様ですか？'],
    ["Could I speak to Mr. Smith?", 'スミスさんとお話しできますか？'],
    ["Hold on a moment, please.", '少々お待ちください。'],
    ["He's not available right now.", '彼は今席を外しています。'],
    ["Can I leave a message?", '伝言をお願いできますか？'],
    ["Could you speak a little more slowly?", 'もう少しゆっくり話していただけますか？'],
    ["I'll call you back later.", '後でかけ直します。'],
    ["Sorry, I think I have the wrong number.", 'すみません、番号を間違えたようです。'],
  ],
  '数字・日付': [
    ['thirteen and thirty', '13と30'],
    ['fifteen and fifty', '15と50'],
    ['nineteen ninety-nine', '1999年'],
    ['two thousand twenty-six', '2026年'],
    ['It costs twelve dollars and fifty cents.', '12ドル50セントです。'],
    ['My birthday is on March third.', '誕生日は3月3日です。'],
    ["The meeting is on Wednesday at eleven thirty.", '会議は水曜日の11時半です。'],
    ['My phone number is five five five, one two three four.', '電話番号は555-1234です。'],
  ],
  'L と R': [
    ['right and light', '右と光'],
    ['read and lead', '読むと導く'],
    ['rice and lice', '米とシラミ'],
    ['really', '本当に'],
    ['The rabbit likes red carrots.', 'ウサギは赤いニンジンが好き。'],
    ['Lily rarely rides the rollercoaster.', 'リリーはめったにジェットコースターに乗らない。'],
    ['grass and glass', '草とガラス'],
    ['correct and collect', '正しいと集める'],
    ['world', '世界'],
    ['I really like the library.', '私は図書館が本当に好きです。'],
    ['Laura rarely rolls her Rs.', 'ローラはめったに巻き舌で R を発音しない。'],
  ],
  'TH の音': [
    ['think and sink', '考えると沈む'],
    ['three', '3'],
    ['thank you', 'ありがとう'],
    ['This is the thing.', 'これがそれだ。'],
    ['I think they thought about that.', '彼らはそれについて考えたと思う。'],
    ['mouth and mouse', '口とネズミ'],
    ['birthday', '誕生日'],
    ['weather and whether', '天気と〜かどうか'],
    ['My brother and father are both healthy.', '兄と父はどちらも健康です。'],
    ['Thirty-three thousand thoughts.', '3万3千の考え。'],
  ],
  'V と B / F と H': [
    ['very and berry', 'とても と ベリー'],
    ['vote and boat', '投票とボート'],
    ['vest and best', 'ベストと最高'],
    ['I love my favorite video.', 'お気に入りの動画が大好き。'],
    ['fan and hand', '扇風機と手'],
    ['food and hood', '食べ物とフード'],
    ['coffee', 'コーヒー'],
    ['Five fine fresh fish.', '5匹の立派な新鮮な魚。'],
  ],
  '母音（長い・短い）': [
    ['ship and sheep', '船と羊'],
    ['live and leave', '住むと去る'],
    ['full and fool', 'いっぱいと愚か者'],
    ['hat and hot and hut', '帽子と熱いと小屋'],
    ['walk and work', '歩くと働く'],
    ['bird', '鳥'],
    ['I want to leave, not live here.', 'ここに住むのではなく、去りたい。'],
    ['The cat sat on the mat.', '猫がマットに座った。'],
  ],
  'つなげて話す': [
    ['Check it out.', 'チェックしてみて。'],
    ['Pick it up.', '拾って。'],
    ['What do you want to do?', '何がしたい？'],
    ['I got to go.', 'もう行かなきゃ。'],
    ['Did you eat yet?', 'もうご飯食べた？'],
    ['Let me know.', '教えてね。'],
    ["I'm going to get a cup of coffee.", 'コーヒーを買ってくるよ。'],
    ['Not at all.', 'どういたしまして／全然。'],
    ['Could you give it to me?', 'それを私にくれますか？'],
  ],
  '早口ことば': [
    ['She sells seashells by the seashore.', '彼女は海辺で貝殻を売る。'],
    ['Red lorry, yellow lorry.', '赤いトラック、黄色いトラック。'],
    ['How can a clam cram in a clean cream can?', 'ハマグリがどうやってきれいなクリーム缶に詰まるの？'],
    ['Peter Piper picked a peck of pickled peppers.', 'ピーター・パイパーは漬けたトウガラシを1ペック摘んだ。'],
    ['How much wood would a woodchuck chuck if a woodchuck could chuck wood?', 'ウッドチャックが木を投げられたら、どれだけ投げるだろう？'],
    ['I scream, you scream, we all scream for ice cream.', 'みんなでアイスクリームを叫ぼう。'],
    ['Fuzzy Wuzzy was a bear.', 'ファジー・ワジーはクマだった。'],
    ['A big black bug bit a big black bear.', '大きな黒い虫が大きな黒いクマを噛んだ。'],
    ['Six slippery snails slid slowly seaward.', '6匹のぬるぬるしたカタツムリがゆっくり海へ滑っていった。'],
    ['Eleven benevolent elephants.', '11頭の優しいゾウ。'],
  ],
};
